const uiText = {
  appTitle: 'Your Month',
  quickAdd: 'Quick Add',
  backendOffline: 'Unable to connect to CHIEF backend.',
  loadingEvents: 'Loading events...',
  emptyToday: 'You’re all clear today.',
  emptyDay: 'Nothing scheduled for this day.',
  modalTitleCreate: 'Create Event',
  modalTitleEdit: 'Event Details',
  labelTitle: 'Title',
  labelDescription: 'Description',
  labelStart: 'Start',
  labelEnd: 'End',
  labelType: 'Type',
  buttonCancel: 'Cancel',
  buttonCreate: 'Create Event',
  buttonSave: 'Save Changes',
  buttonDelete: 'Delete',
  deleteConfirmTitle: 'Delete Event?',
  deleteConfirmMessage: 'Are you sure you want to delete this event? This action cannot be undone.',
  deleteConfirmCancel: 'Cancel',
  deleteConfirmAction: 'Delete',
  comingSoon: 'Coming soon',
  commandPlaceholder: '> Chief...',
  selectedDay: 'Selected Day',
  eventTypeAria: 'Event type',
}

export default uiText
