const uiText = {
  appTitle: 'Your Month',
  quickAdd: 'Quick Add',
  backendOffline: 'Unable to connect to CHIEF backend.',
  loadingEvents: 'Loading events...',
  emptyToday: 'You’re all clear today.',
  emptyDay: 'Nothing scheduled for this day.',
  modalTitleCreate: 'Create Event',
  modalTitleEdit: 'Event Details',
  labelTitle: 'Title',
  labelDescription: 'Description',
  labelStart: 'Start',
  labelEnd: 'End',
  labelType: 'Type',
  labelCategory: 'Category',
  labelPriority: 'Priority',
  labelCompleted: 'Completed',
  labelCreatedAt: 'Created',
  labelUpdatedAt: 'Updated',
  buttonCancel: 'Cancel',
  buttonCreate: 'Create Event',
  buttonSave: 'Save Changes',
  manualEvent: 'Manual Event',
  smartAdd: 'Smart Add',
  smartAddTitle: 'Smart Add',
  smartAddMessage: 'Enter an event description (e.g. "Tomorrow 5pm team sync"). The parser will show a preview before creating the event.',
  buttonDelete: 'Delete',
  deleteConfirmTitle: 'Delete Event?',
  deleteConfirmMessage: 'Are you sure you want to delete this event? This action cannot be undone.',
  deleteConfirmCancel: 'Cancel',
  deleteConfirmAction: 'Delete',
  comingSoon: 'Coming soon',
  commandPlaceholder: '> Chief...',
  selectedDay: 'Selected Day',
  emptyPlanned: 'Nothing planned for this day.',
  emptyEnjoy: 'Enjoy your free day.',
  eventTypeAria: 'Event type',
  previousMonth: 'Previous',
  nextMonth: 'Next',
  today: 'Today',
  monthView: 'Month',
  weekView: 'Week',
  moreEvents: '+{count} more',
  monthPickerTitle: 'Pick a month',
  yearPickerTitle: 'Pick a year',
  keyboardHelp: 'Keyboard shortcuts: N = New event, T = Today, ←/→ = Navigate',
}

export default uiText
